### ISSUE TITLE
Readme Clarification for ID Attribute

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-text#20]
Reproduction Steps
Create a rise-text component instance in a Template without the use of an ID attribute. 

What you expected to happen.
I actually would not expect it to work. I think we just need to clarify in the Readme that this is a required field.

Actual Results
The component will show up in the Template but when you go to edit it, the field will be blank https://www.screencast.com/t/Bv0NZZ4A92 and you can not edit it.

**Comment by olegrise** [comment]
Fixed
