### ISSUE TITLE
Font size cannot be set above 200px

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-text#30]
**What should happen**

When adjusting the font size, the starting value should match the `fontsize` attribute set in the Template, and allow for a certain amount of scaling up (possibly around 150 - 200%). 

**What currently happens**

It looks like the font size is maxed out at 200px. It can't be adjusted higher using the UI and does not match the size set in the `fontsize` attribute.

**Steps to recreate**

You can see this in Easter Template in the stage 7 editor: https://apps-stage-7.risevision.com/templates/edit/d9f9e080-deaf-497a-b408-6c9f48862f01/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

The value in the attribute is 300px but the slider stops at 200px. I think it would be better to have the slider start at the attribute value and have the option to go up to 150 - 200% the size based on the starting value. We have a few Templates where there is a small amount of text with a large font size like this one, New Year and Christmas ones. Thanks!

**Comment by fjvallarino** [comment]
Closing based on the discussion here: https://trello.com/c/1ZVpQBaZ/7479-issue-30-font-size-cannot-be-set-above-200px-2

Please reopen if needed!
